### ISSUE TITLE
Kepler-Operator CSV doesn't use port for exposing metrics

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-operator#145]
When deploying Kepler Operator using bundle it deploys a controller manager pod and service. Current CSV doesn't consider containerPort in case of the manager's [deployment](https://github.com/sustainable-computing-io/kepler-operator/blob/a8b249cf67043068a364c3b91f82e71c4af62ff1/bundle/manifests/kepler-operator.clusterserviceversion.yaml#L214). Related to that the service [yaml](https://github.com/sustainable-computing-io/kepler-operator/blob/v1alpha1/bundle/manifests/kepler-operator-controller-manager-metrics-service_v1_service.yaml) only consider's port [exposed](https://github.com/sustainable-computing-io/kepler-operator/blob/a8b249cf67043068a364c3b91f82e71c4af62ff1/bundle/manifests/kepler-operator.clusterserviceversion.yaml#L199) for kube-rbac proxy. Due to this, it's hard for anyone who wants to view the metrics exposed by controller manager like `controller_runtime` etc. 

The CSV and service yaml should be updated and reflect the required port so that we can do a port-forward/create route from service and able to view the metrics.

**Comment by sthaha** [comment]
Is the cluster monitoring able to scrape off controller-manager if you add a servicemonitor? RBAC has been added for a reason  and going forward, kepler will also be deployed with kube-rbac-proxy which will prevent anyone in the cluster to read kepler metrics.

**Comment by vprashar2929** [comment]
So How I got this to work was to add `containerPorts` in the CSV in case of manager and change service yaml to point the exposed port and deploy. 
Post that I was able to do port-forwarding on that port and see the metrics exposed.

I haven't tried adding serviceMonitor and see the metrics.

**Comment by vprashar2929** [comment]
I tried creating a service monitor pointing to the kepler-operator-controller-manager-metrics-service. Below is my servicemonitor for reference:
```
apiVersion: monitoring.coreos.com/v1
 kind: ServiceMonitor
 metadata:
   labels:
     app.kubernetes.io/name: service
     app.kubernetes.io/part-of: kepler-operator
     control-plane: controller-manager
   name: exporter-sm
   namespace: openshift-operators
 spec:
   endpoints:
   - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token                                                                                                                                                                          
     path: /metrics
     port: https
     scheme: https
     tlsConfig:
       insecureSkipVerify: true
   selector:
     matchLabels:
       app.kubernetes.io/name: service
       app.kubernetes.io/part-of: kepler-operator
       control-plane: controller-manager
```
Since kube-rbac listen to the secure address I tried providing a token to access it but prometheus-operator skip servicemonitor and threw the below warning:
```
level=warn ts=2023-08-17T10:55:41.325121264Z caller=operator.go:1917 component=prometheusoperator msg="skipping servicemonitor" error="it accesses file system via bearer token file which Prometheus specification prohibits" servicemonitor=openshift-operators/exporter-sm namespace=openshift-user-workload-monitoring prometheus=user-workload
```

Am I missing something here?
