### ISSUE TITLE
Kepler Exporter not installing on Infra nodes

### ISSUE THREAD

**Issue by AdrianHammond** [sustainable-computing-io/kepler-operator#158]
I have installed the 0.61 version of the operator on a 7 node cluster (ROSA on demo.redhat.com). 3 x control plane, 2 x compute and 2 x infra/compute nodes. I see only five kepler exporter nodes running. Kepler is not running on the infra/compute nodes.

**Comment by vimalk78** [comment]
reason is that on ROSA clusters, the infra nodes have a `NoSchedule` taint

```
spec:
  providerID: aws:///us-east-2a/i-088602fb396310f59
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
```

sending PR for adding toleration
