### ISSUE TITLE
Expose config for collecting cgroup and kubelet metrics in kepler exporter API

### ISSUE THREAD

**Issue by vimalk78** [sustainable-computing-io/kepler-operator#202]
enable/dsiable collecting cgroup and kubelet metrics by exposing bool  config params in Exporter API.

Ref: https://github.com/sustainable-computing-io/kepler/pull/876/files
        https://github.com/sustainable-computing-io/kepler/issues/901

**Comment by vimalk78** [comment]
@rootfs @sunya-ch need your input here

**Comment by sunya-ch** [comment]
Could you clarify more about this issue? Do you mean to expose it via the  Kepler command arguments not via the config map?

**Comment by vimalk78** [comment]
i mean expose it in `ExporterSpec`

```
apiVersion: kepler.system.sustainable.computing.io/v1alpha1
kind: Kepler
metadata:
  labels:
    app.kubernetes.io/name: kepler
    app.kubernetes.io/instance: kepler
    app.kubernetes.io/part-of: kepler-operator
  name: kepler
spec:
  exporter:
    port: 9103
    enableCGroupMetrics: true
    enableKubeletMetrics: true
```
these values will be used to populate the kepler configmap

**Comment by sunya-ch** [comment]
Thank you. The key of the configmap variables are all listed here: https://github.com/sustainable-computing-io/kepler/blob/02c16c1e223e32b1d1f20f3c7ad8e8959eb2fd87/pkg/config/config.go#L77.

**Comment by sthaha** [comment]
@vimalk78 How about something like this. This allows us to add additional fields to each of the metric later on.  E.g. say in future, cgroup can not only be enabled but also a filter can be applied on the metrics, this would allow for change to be
added  without  breaking the api. Also grouping under metrics may allow us to add config that applies to all metrics (if any) in 
future without breaking api


```yaml
exporter:
  metrics:  # keep all metrics under MetricSpec
    cgroups:  # feature specific config
        enabled: true
    kubelet:
        enabled: true
    foobar:
       enabled: true
       additional: config
```

In general, I am wary of boolean flags.
