### ISSUE TITLE
Add proper validation for redfish secret name

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-operator#372]
Currently while creating a Kepler instance we specify redfish secret. The secret name is not validated according to resource naming standards.
For eg:
```
      redfish:
        probeInterval: 1m0s
        secretRef: ' '
        skipSSLVerify: false
```
still treated as valid but ideally it should not
