### ISSUE TITLE
Kepler status shows incorrect lastTransitionTime

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-operator#373]
When the Kepler instance is created under the exporter status the `lastTransitionTime` of status is the same irrespective of the actual timestamp. It picks the most recent one and updates all the with recent timestamp
For eg:
```
    exporter:
      conditions:
      - lastTransitionTime: "2024-03-11T11:23:36Z"
        message: Redfish secret " " configured, but not found in "kepler-operator"
          namespace
        observedGeneration: 2
        reason: ReconcileError
        status: "False"
        type: Reconciled
      - lastTransitionTime: "2024-03-11T11:23:36Z"
        message: DaemonSet.apps "kepler" not found
        observedGeneration: 2
        reason: DaemonSetNotFound
        status: "False"
        type: Available
```
shows `lastTransitionTime` as the same even when those two events occurred on different timestamps
