### ISSUE TITLE
Decide to update or remove the Installation guide links

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-operator#550]
We expose the installation guide links in our CSV that points to older/depracated docs. We have to decide either remove these until we update the docs or update them to point to repo's README

```
  links:
  - name: Installation Guide
    url: https://sustainable-computing.io/installation/community-operator/
  - name: Kepler Project
    url: https://sustainable-computing.io/

```
